#set( $symbol_pound = '#' )
#set( $symbol_dollar = '$' )
#set( $symbol_escape = '\' )
status = ${symbol_dollar}{sys:LOG4J_STATUS:-warn}
name = ConsoleConfig

${symbol_pound} Define the appender
appender.console.type = Console
appender.console.name = STDOUT
appender.console.layout.type = PatternLayout
${symbol_pound} Ensure the pattern is on a SINGLE line with no trailing spaces
${symbol_pound}property.appenderPattern=${symbol_dollar}{sys:loggerPattern:-%msg%n}
appender.console.layout.pattern = ${symbol_dollar}{sys:loggerPattern:-%msg%n}

${symbol_pound} Define the root logger
rootLogger.level = info
rootLogger.appenderRef.stdout.ref = STDOUT